Final Touchups
MichelRahme/ConcordiaNavigation pull request #185
Opened 2020-04-13 22:34 UTC by WindOfRussia

## Description

Final tweaks and changes to the app following heavy simulated and real world testing on various devices. Fixes include some current location search & poi tweaks, added documentation blocks, added some french keywords, added some indoor navigation tests, and general code clean up.

## Related Issues

2020-04-13 23:29 UTC, EvanMateo7 requested changes
Small test failing from commit https://github.com/MichelRahme/ConcordiaNavigation/commit/bb4530f05b7fbdbdafb5d8c121989281e3a4fb82

2020-04-14 01:32 UTC, EvanMateo7 approved these changes

2020-04-14 01:35 UTC, EvanMateo7 commented on test/services/dijkstra_json_test.dart
> +      List<Node> result = dijkstra.pathTo("MB1.301", "MB1.210", accessible: true);
Wrong result object causing test to fail

2020-04-14 03:03 UTC, andrelegault approved these changes

2020-04-14 03:03 UTC, merged